### ISSUE TITLE
Cannot equip Kaer Morhen armor in Originations Modpack

### ISSUE THREAD

**Issue by MutantMiner300** [Clark919/WitcherOrigin#1]
Exactly what title says, I am the witcher origin and I cannot equip any of the origin specific armors. I'm guessing its because of the TieredZ mod

**Comment by Clark919** [comment]
Thanks for the report. I'll look into this when I get the opportunity.

**Comment by Clark919** [comment]
Since this issue is not related to the Witcher Mod directly and rather a compatibility issue with Origination, would you mind re-opening a ticket on the Origination issues page? Apologies for the inconvenience: https://github.com/Clark919/Origination-Modpack/issues
